# Generated by Django 5.1.3 on 2024-12-09 14:05

import GardeningCareServicesApp.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_serviceproviderprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeownerprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Only digits spaces and - allowed', max_length=15, null=True, validators=[GardeningCareServicesApp.accounts.validators.PhoneNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Only digits spaces and - allowed', max_length=15, null=True, validators=[GardeningCareServicesApp.accounts.validators.PhoneNumberValidator()]),
        ),
    ]
